# Chief - GoReleaser Configuration
# https://goreleaser.com
#
# Build targets:
#   - darwin/amd64, darwin/arm64
#   - linux/amd64, linux/arm64
#   - windows/amd64
#
# Local snapshot (builds all platforms):
#   goreleaser release --snapshot --clean
#
# Single target (current platform only):
#   goreleaser build --snapshot --clean --single-target

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/chief
    binary: chief
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}

archives:
  - id: chief-archive
    formats:
      - tar.gz
    # Use zip for Windows
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    # Files to include in the archive
    files:
      - LICENSE*
      - README*

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

# Announce release notes style
release:
  draft: false
  prerelease: auto
  name_template: "Chief v{{.Version}}"

# Homebrew tap configuration
brews:
  - name: chief
    # Repository to push the formula to
    repository:
      owner: minicodemonkey
      name: homebrew-chief
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: "https://minicodemonkey.github.io/chief/"
    description: "Autonomous agent loop for working through PRDs with Claude Code"
    license: "MIT"
    # Custom install script
    install: |
      bin.install "chief"
    # Test block
    test: |
      assert_match "chief", shell_output("#{bin}/chief --version")
    # Skip upload on snapshot builds
    skip_upload: auto
